# Changes here will be overwritten by Copier
_commit: v0.0.51-4-g11bbc9a
_src_path: gh:LabAutomationAndScreening/copier-aws-central-infrastructure.git
aws_identity_center_id: d-9067c20053
aws_org_home_region: us-east-1
aws_organization_repo_name: aws-organization
aws_production_account_id: 038462771856
aws_region_for_stack: us-east-1
central_infra_github_organization_name: ejfine
cloud_courier_infra_repo_name: cloud-courier-infrastructure
configure_cloud_courier: true
create_private_subnet: false
description: Manage central infra for this AWS org
github_tokens_created: true
identity_center_production_account_id: '872515268414'
import_github_aws_org_repos: false
initial_github_admin: ejfine
initial_iac_management_deploy_occurred: true
is_open_source: true
manage_github_repos: true
manage_okta: false
python_package_registry: PyPI
python_version: 3.13.1
repo_name: aws-central-infrastructure
repo_org_name: ejfine
ssh_port_number: 52368
use_repo_secret_for_github_iac_tokens: true
use_staging_environment: false
use_windows_in_ci: false

