# ============== WARNING ==============================================================================
# File is managed by copier template: gh:LabAutomationAndScreening/copier-base-template.git
# See .config/.copier-managed-files.json for details.
#
# You are welcome to make changes to this file in your repo if they are custom to your project,
# but if the change should be shared with other projects, please backport it to the template repo.
# =====================================================================================================
[project]
name = "aws-central-infrastructure"
version = "0.1.0"
description = "Managing the non-management-account Central Infrastructure for an AWS Organization"

readme = "README.md"
requires-python = ">=3.13.1"

dependencies = [
    # Specific to this template


    # Managed by upstream template
    "pyright>=1.1.411",
    "pyrefly>=1.1.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-randomly>=4.1.0",
    "pytest-mock>=3.15.1",
    "syrupy>=5.3.4",
    "pulumi>=3.245.0",
    "pulumi-aws>=7.32.0",
    "pulumi-aws-native>=1.68.0",
    "pulumi-command>=1.2.1",
    "pulumi-github>=6.13.1",
    "ephemeral-pulumi-deploy>=0.0.7",
    "lab-auto-pulumi>=0.2.3",
    "boto3>=1.42.92",
    "boto3-stubs[all]>=1.42.92",
    "pydantic>=2.13.4",
]

[tool.uv]
package = true
