ROOT_GITHUB_ADMIN_USERNAME = "ejfine"
GITHUB_TOKENS_CREATED = True
USE_REPO_SECRET_FOR_GITHUB_IAC_TOKENS = True
AWS_ORGANIZATION_REPO_NAME = "aws-organization"
ACTIVELY_IMPORT_AWS_ORG_REPOS = False
AWS_ORG_REPOS_SUCCESSFULLY_IMPORTED = False
ALLOW_ADMIN_BYPASS_FOR_AWS_ORG_REPOS = False
