CENTRAL_INFRA_REPO_NAME = "aws-central-infrastructure"
CLOUD_COURIER_INFRA_REPO_NAME = "cloud-courier-infrastructure"
CENTRAL_INFRA_PROD_ACCOUNT_ID = "038462771856"
IDENTITY_CENTER_ACCOUNT_ID = "872515268414"
CENTRAL_INFRA_GITHUB_ORG_NAME = "ejfine"
CONFIGURE_CLOUD_COURIER = True
